# on: 
#   push: 
#     branches: 
#       - main
# name: ðŸš€ Deploy TC-app to production on Antagonist (skcvolleybal.nl/tc-app)
# jobs:
#   web-deploy:
#     name: ðŸŽ‰ Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: ðŸšš Get latest code
#       uses: actions/checkout@v2
    
#     - name: ðŸ“‚ Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.3.3
#       with:
#         server: ftp.skcvolleybal.nl
#         username: ${{ secrets.ftp_username_disabled }}
#         password: ${{ secrets.ftp_password_disabled }}
        # Server-dir not necessary: the FTP account only has rights to write in /public_html/scripts. See webhost control panel for FTP. 
